/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.Arrays;
import javax.swing.JOptionPane;
import lson.Lson;
import tree.Tree;

/**
 *
 * @author Luis G
 */
public class SortApp extends javax.swing.JFrame {

    /**
     * Creates new form SortApp
     */
    Lson lson = new Lson();
    Sort sort = new Sort();
    Tree tree = new Tree();
    int[] array;
    int[] arr;

    public SortApp() {
        initComponents();
        setLocationRelativeTo(null);
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shellSort = new javax.swing.JButton();
        naturalMerge = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        arraySize = new javax.swing.JTextField();
        maxValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bubble = new javax.swing.JButton();
        quickSort = new javax.swing.JButton();
        radix = new javax.swing.JButton();
        intercalation = new javax.swing.JButton();
        directMerge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shellSort.setText("ShellSort");
        shellSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shellSortActionPerformed(evt);
            }
        });

        naturalMerge.setText("Mezcla natural");
        naturalMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naturalMergeActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Tamaño del arreglo");

        jLabel2.setText("Valor maximo");

        bubble.setText("Burbuja");
        bubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubbleActionPerformed(evt);
            }
        });

        quickSort.setText("QuickSort");
        quickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickSortActionPerformed(evt);
            }
        });

        radix.setText("Radix");
        radix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radixActionPerformed(evt);
            }
        });

        intercalation.setText("Intercalación");
        intercalation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercalationActionPerformed(evt);
            }
        });

        directMerge.setText("Mezcla directa");
        directMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directMergeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(arraySize, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bubble)
                        .addGap(18, 18, 18)
                        .addComponent(quickSort)
                        .addGap(18, 18, 18)
                        .addComponent(shellSort)
                        .addGap(18, 18, 18)
                        .addComponent(radix)
                        .addGap(18, 18, 18)
                        .addComponent(intercalation)
                        .addGap(18, 18, 18)
                        .addComponent(directMerge)
                        .addGap(18, 18, 18)
                        .addComponent(naturalMerge)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shellSort)
                    .addComponent(bubble)
                    .addComponent(quickSort)
                    .addComponent(radix)
                    .addComponent(intercalation)
                    .addComponent(directMerge)
                    .addComponent(naturalMerge))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arraySize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shellSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shellSortActionPerformed
        generateArray();
        lson = sort.shell(arr);
        setText();
    }//GEN-LAST:event_shellSortActionPerformed

    private void naturalMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naturalMergeActionPerformed
        generateArray();
        lson = sort.naturalMerge(arr);
        setText();
    }//GEN-LAST:event_naturalMergeActionPerformed

    private void bubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubbleActionPerformed
        generateArray();
        lson = sort.bubble(arr);
        setText();
    }//GEN-LAST:event_bubbleActionPerformed

    private void quickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickSortActionPerformed
        generateArray();
        lson = sort.quickSort(arr);
        setText();
    }//GEN-LAST:event_quickSortActionPerformed

    private void radixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radixActionPerformed
        generateArray();
        lson = sort.radix(arr);
        setText();
    }//GEN-LAST:event_radixActionPerformed

    private void intercalationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercalationActionPerformed
        int[] array1 = generateArray();
        int[] array2 = generateArray();
        lson = sort.bubble(array1);
        jTextArea1.setText("  El primer arreglo ordenado es:\n\n  ");
        jTextArea1.append(Arrays.toString(lson.getArray()) + "\n\n");
        lson = sort.bubble(array2);
        jTextArea1.append("  El segundo arreglo ordenado es:\n\n  ");
        jTextArea1.append(Arrays.toString(lson.getArray()) + "\n\n");
        lson = sort.intercalation(array1, array2);
        jTextArea1.append("  El arreglo ordenado por el metodo de " + lson.getElementById(0) + " es:\n\n  ");
        jTextArea1.append(Arrays.toString(lson.getArray()));
        tree(lson.getArray());
    }//GEN-LAST:event_intercalationActionPerformed

    private void directMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directMergeActionPerformed
        generateArray();
        lson = sort.directMerge(arr);
        setText();
    }//GEN-LAST:event_directMergeActionPerformed

    private int[] generateArray() {
        if (arraySize.getText().equals("") && maxValue.getText().equals("")) {
            array = sort.createRandomArray(10, 10);
            arr = array.clone();
        } else if (maxValue.getText().equals("")) {
            try {
                array = sort.createrandomArray(Integer.parseInt(arraySize.getText()));
                arr = array.clone();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Solo se aceptan numeros :'v", "Error", 0);
            }
        } else {
            try {
                array = sort.createRandomArray(Integer.parseInt(arraySize.getText()), Integer.parseInt(maxValue.getText()));
                arr = array.clone();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Solo se aceptan numeros :'v", "Error", 0);
            }
        }
        return arr;
    }

    private void setText() {
        jTextArea1.setText("  El arreglo desordenado es:\n\n  ");
        jTextArea1.append(Arrays.toString(array) + "\n\n");
        jTextArea1.append("  El arreglo ordenado por el metodo de " + lson.getElementById(0) + " es:\n\n  ");
        jTextArea1.append(Arrays.toString(lson.getArray()));
        tree(lson.getArray());
    }

    private void tree(int[] array) {
        tree.add(array);
        jTextArea1.append("\n\n  El arreglo ordenado por arbol en pre orden es:\n\n  ");
        jTextArea1.append(Arrays.toString(tree.preOrder()));
        jTextArea1.append("\n\n  El arreglo ordenado por arbol en post orden es:\n\n  ");
        jTextArea1.append(Arrays.toString(tree.postOrder()));
        jTextArea1.append("\n\n  El arreglo ordenado por arbol en in orden es:\n\n  ");
        jTextArea1.append(Arrays.toString(tree.inOrder()) + "\n\n");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arraySize;
    private javax.swing.JButton bubble;
    private javax.swing.JButton directMerge;
    private javax.swing.JButton intercalation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField maxValue;
    private javax.swing.JButton naturalMerge;
    private javax.swing.JButton quickSort;
    private javax.swing.JButton radix;
    private javax.swing.JButton shellSort;
    // End of variables declaration//GEN-END:variables
}
