/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabladb;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static tabladb.Config.*;
import static tabladb.Connector.*;
import static tabladb.Validate.*;

/**
 *
 * @author Luis G
 */
public class Alumnos extends javax.swing.JFrame {

    /**
     * Creates new form Alumnos
     */
    DefaultTableModel model = new DefaultTableModel();
    ResultSet data;

    public Alumnos() {
        initComponents();
        this.table.setEnabled(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.pack();
        this.titulo.setText(TITULO);
        user.setText("Usuario: " + session);
        agregar.setBackground(DEFAULT);
        eliminarPorId.setBackground(DANGER);
        model.addColumn("id");
        model.addColumn("Nombre");
        model.addColumn("Apellido Paterno");
        model.addColumn("Apellido Materno");
        model.addColumn("Sexo");
        model.addColumn("Edad");
        model.addColumn("Dirección");
        model.addColumn("Teléfono");
        model.addColumn("Correo");
        table.setModel(model);
        /*try {
            if (BCrypt.checkpw("Luis", hashed)) {
                System.out.println("It matches");
            } else {
                System.out.println("It does not match");
            }
        } catch (Exception e) {
        }*/
        loadData();
    }

    private void loadData() {
        model.setNumRows(0);
        data = getData("SELECT * FROM alumnos");
        try {
            while (data.next()) {
                model.addRow(new Object[]{data.getInt(1), data.getString(2), data.getString(3), data.getString(4), data.getString(5), data.getInt(6), data.getString(7), data.getString(8), data.getString(9)});
            }
            close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        card = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        apellidoMaternoError = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        edadError = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        direccionError = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        sexoLabel = new javax.swing.JLabel();
        sexoError = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        telefonoError = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellidoPaternoLabel = new javax.swing.JLabel();
        apellidoPaterno = new javax.swing.JTextField();
        apellidoMaternoLabel = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        correoError = new javax.swing.JLabel();
        apellidoMaterno = new javax.swing.JTextField();
        edadLabel = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        apellidoPaternoError = new javax.swing.JLabel();
        nombreError = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        eliminarPorId = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        eliminarTabla = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabla de alumnos");
        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Apellido Paterno", "Apellido Materno", "Sexo", "Edad", "Direccion", "Teléfono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        formPanel.setBackground(new java.awt.Color(255, 255, 255));

        apellidoMaternoError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        apellidoMaternoError.setForeground(new java.awt.Color(255, 0, 0));

        direccionLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        direccionLabel.setText("Dirección");

        edadError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edadError.setForeground(new java.awt.Color(255, 0, 0));

        direccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        direccionError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        direccionError.setForeground(new java.awt.Color(255, 0, 0));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        sexoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sexoLabel.setText("Sexo");

        sexoError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sexoError.setForeground(new java.awt.Color(255, 0, 0));

        telefonoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefonoLabel.setText("Teléfono");

        telefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        telefonoError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefonoError.setForeground(new java.awt.Color(255, 0, 0));

        nombreLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nombreLabel.setText("Nombre");

        correoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        correoLabel.setText("Correo");

        nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        apellidoPaternoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        apellidoPaternoLabel.setText("Apellido Paterno");

        apellidoPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        apellidoMaternoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        apellidoMaternoLabel.setText("Apellido Materno");

        correo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        correoError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        correoError.setForeground(new java.awt.Color(255, 0, 0));

        apellidoMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        edadLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edadLabel.setText("Edad");

        edad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        apellidoPaternoError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        apellidoPaternoError.setForeground(new java.awt.Color(255, 0, 0));

        nombreError.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nombreError.setForeground(new java.awt.Color(255, 0, 0));

        agregar.setBackground(new java.awt.Color(56, 126, 245));
        agregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.setBorder(null);
        agregar.setBorderPainted(false);
        agregar.setContentAreaFilled(false);
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.setFocusPainted(false);
        agregar.setOpaque(true);
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                agregarMouseReleased(evt);
            }
        });
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLabel)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoLabel)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apellidoPaternoLabel)
                    .addComponent(apellidoPaternoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(direccionLabel)
                    .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(direccionError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidoPaterno))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apellidoMaternoLabel)
                    .addComponent(apellidoMaternoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefonoLabel)
                    .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(apellidoMaterno)
                    .addComponent(telefonoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(correoLabel)
                    .addComponent(edadLabel)
                    .addComponent(edad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(edadError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correo)
                    .addComponent(correoError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(nombreLabel)
                        .addGap(6, 6, 6)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(nombreError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(sexoLabel)
                        .addGap(6, 6, 6)
                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(sexoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(edadLabel)
                        .addGap(6, 6, 6)
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(edadError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(correoLabel)
                        .addGap(6, 6, 6)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(correoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(apellidoMaternoLabel)
                                .addGap(6, 6, 6)
                                .addComponent(apellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(apellidoMaternoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(telefonoLabel)
                                .addGap(6, 6, 6)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(telefonoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(apellidoPaternoLabel)
                                .addGap(6, 6, 6)
                                .addComponent(apellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(apellidoPaternoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(direccionLabel)
                                .addGap(6, 6, 6)
                                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(direccionError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        eliminarPorId.setBackground(new java.awt.Color(245, 61, 61));
        eliminarPorId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        eliminarPorId.setForeground(new java.awt.Color(255, 255, 255));
        eliminarPorId.setText("Eliminar por id");
        eliminarPorId.setBorder(null);
        eliminarPorId.setBorderPainted(false);
        eliminarPorId.setContentAreaFilled(false);
        eliminarPorId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarPorId.setFocusPainted(false);
        eliminarPorId.setOpaque(true);
        eliminarPorId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarPorIdMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eliminarPorIdMouseReleased(evt);
            }
        });
        eliminarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPorIdActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        eliminarTabla.setBackground(new java.awt.Color(245, 61, 61));
        eliminarTabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        eliminarTabla.setForeground(new java.awt.Color(255, 255, 255));
        eliminarTabla.setText("Eliminar toda la tabla");
        eliminarTabla.setBorder(null);
        eliminarTabla.setBorderPainted(false);
        eliminarTabla.setContentAreaFilled(false);
        eliminarTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarTabla.setFocusPainted(false);
        eliminarTabla.setOpaque(true);
        eliminarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarTablaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eliminarTablaMouseReleased(evt);
            }
        });
        eliminarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTablaActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo.setText("Lista de alumnos de 4ISC11 :v");

        user.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        user.setText("Usuario: ");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(316, 316, 316))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(eliminarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eliminarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(user)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user)
                .addGap(3, 3, 3)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMousePressed
        this.agregar.setBackground(DEFAULT_PRESSED);
    }//GEN-LAST:event_agregarMousePressed

    private void agregarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseReleased
        this.agregar.setBackground(DEFAULT);
    }//GEN-LAST:event_agregarMouseReleased

    private void eliminarPorIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarPorIdMousePressed
        this.eliminarPorId.setBackground(DANGER_PRESSED);
    }//GEN-LAST:event_eliminarPorIdMousePressed

    private void eliminarPorIdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarPorIdMouseReleased
        this.eliminarPorId.setBackground(DANGER);
    }//GEN-LAST:event_eliminarPorIdMouseReleased

    private void eliminarTablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTablaMousePressed
        this.eliminarTabla.setBackground(DANGER_PRESSED);
    }//GEN-LAST:event_eliminarTablaMousePressed

    private void eliminarTablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTablaMouseReleased
        this.eliminarTabla.setBackground(DANGER);
    }//GEN-LAST:event_eliminarTablaMouseReleased

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (lgValidate()) {
            executeQuery("INSERT INTO alumnos (nombre, apellido_paterno, apellido_materno, sexo, edad, direccion, telefono, correo) VALUES ('"
                    + nombre.getText() + "', '" + apellidoPaterno.getText() + "', '" + apellidoMaterno.getText() + "', '" + sexo.getSelectedItem() + "', '"
                    + Integer.parseInt(edad.getText()) + "', '" + direccion.getText() + "', '" + telefono.getText() + "', '" + correo.getText() + "')");
            loadData();
            nombre.setText("");
            apellidoPaterno.setText("");
            apellidoMaterno.setText("");
            edad.setText("");
            direccion.setText("");
            telefono.setText("");
            correo.setText("");
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTablaActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Seguro que quiere eliminar toda la tabla?", "Eliminar tabla", 1) == 0) {
            executeQuery("TRUNCATE alumnos");
            loadData();
        }
    }//GEN-LAST:event_eliminarTablaActionPerformed

    private void eliminarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPorIdActionPerformed
        try {
            int idQuery = Integer.parseInt(id.getText());
            if (JOptionPane.showConfirmDialog(null, "Seguro que quiere eliminar el registro?", "Eliminar registro", 1) == 0) {
                executeQuery("DELETE FROM alumnos WHERE id = " + idQuery);
                loadData();
                id.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El id debe de ser un número :'v", "Error", 0);
        }
    }//GEN-LAST:event_eliminarPorIdActionPerformed

    private boolean lgValidate() {
        boolean nombreValid, apellidoPaternoValid, apellidoMaternoValid, edadValid, direccionValid, telefonoValid, correoValid;
        //validación del nombre
        nombreValid = validateText(nombre, nombreError);
        //validación del apellido paterno
        apellidoPaternoValid = validateText(apellidoPaterno, apellidoPaternoError);
        //validación del apellido materno
        apellidoMaternoValid = validateText(apellidoMaterno, apellidoMaternoError);
        //validacion de la edad
        edadValid = validateNumber(edad, edadError);
        //validación de la dirección
        if (direccion.getText().equals("")) {
            direccionError.setText(NULL_DATA_ERROR);
            direccionValid = false;
        } else {
            direccionValid = true;
        }
        //validación del teléfono
        telefonoValid = validateNumber(telefono, telefonoError);
        //validación del correo
        correoValid = validateEmail(correo, correoError);
        if (nombreValid && apellidoPaternoValid && apellidoMaternoValid && edadValid
                && direccionValid && telefonoValid && correoValid) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField apellidoMaterno;
    private javax.swing.JLabel apellidoMaternoError;
    private javax.swing.JLabel apellidoMaternoLabel;
    private javax.swing.JTextField apellidoPaterno;
    private javax.swing.JLabel apellidoPaternoError;
    private javax.swing.JLabel apellidoPaternoLabel;
    private javax.swing.JPanel card;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel correoError;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionError;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel edadError;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JButton eliminarPorId;
    private javax.swing.JButton eliminarTabla;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTextField id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreError;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JLabel sexoError;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JTable table;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoError;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
